// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: list.sql

package db

import (
	"context"
)

const createList = `-- name: CreateList :one
INSERT INTO lists (title, currency) VALUES ($1, $2) RETURNING id, currency, title, created_at
`

type CreateListParams struct {
	Title    string
	Currency Currency
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (List, error) {
	row := q.db.QueryRow(ctx, createList, arg.Title, arg.Currency)
	var i List
	err := row.Scan(
		&i.ID,
		&i.Currency,
		&i.Title,
		&i.CreatedAt,
	)
	return i, err
}
