// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO app.sessions (user_id, expires_at, user_agent, ip) VALUES ($1, $2, $3, $4) RETURNING id, user_id, created_at, expires_at, revoked_at, user_agent, ip
`

type CreateSessionParams struct {
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	UserAgent pgtype.Text
	Ip        pgtype.Text
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (AppSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.Ip,
	)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, created_at, expires_at, revoked_at, user_agent, ip FROM app.sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (AppSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i AppSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.Ip,
	)
	return i, err
}
